### PR TITLE
keyctl.c: use key_is_negative(key) instead of KEY_FLAG_NEGATIVE

### PR DESCRIPTION
**Pull request by Grimler91**
KEY_FLAG_NEGATIVE was removed in commit https://github.com/Vaughnellope/android_kernel_samsung_universal8895/commit/8a004caec12bf241e567e36404012.

### CODE REVIEW

**Comment by Vaughnellope** [comment]
I'll take a look into this, thanks.

**Comment by Grimler91** [comment]
I see now that a second commit was automatically added to this PR. 

Both of them were needed when I tried building LineageOS anyways.

**Comment by Vaughnellope** [comment]
Build just fine without the 1st commit, and we dont need the 2nd commit.

**Comment by Grimler91** [comment]
Interesting! Maybe I'm doing something wrong. 
I tried it again and could reproduce the errors though. 

Without the keyctl.c fix I get something like this: 
```
kernel/samsung/universal8895/security/keys/keyctl.c: In function 'keyctl_read_key':
kernel/samsung/universal8895/security/keys/keyctl.c:753:15: error: 
'KEY_FLAG_NEGATIVE' undeclared (first use in this function)
if (test_bit(KEY_FLAG_NEGATIVE, &key->flags))
             ^
../../../../../../kernel/samsung/universal8895/security/keys/keyctl.c:753:15: 
note: each undeclared identifier is reported only once for each function it appears in
/work2/projects/Android/cm/system/kernel/samsung/universal8895/scripts/Makefile.build:269: recipe for target 'security/keys/keyctl.o' failed
make[3]: *** [security/keys/keyctl.o] Error 1
```

Doing a `grep -r KEY_FLAG_NEGATIVE .` from the root of the android_kernel_samsung_universal8895 shows that KEY_FLAG_NEGATIVE isn't defined anywhere. Looking into the git history I can see that it was removed in [8a004ca](https://github.com/Vaughnellope/android_kernel_samsung_universal8895/commit/8a004caec12bf241e567e3640401256cc9bc2e45) everywhere except in keyctl.c.

---

Applying my suggested fix makes the build continue until this error: 
```
firmware/exynos8895_acpm_dvfs.fw.gen.S: Assembler messages:
firmware/exynos8895_acpm_dvfs.fw.gen.S:5: Error: file not found: firmware/exynos8895_acpm_dvfs.fw
/work2/projects/Android/cm/system/kernel/samsung/universal8895/scripts/Makefile.build:367:
recipe for target 'firmware/exynos8895_acpm_dvfs.fw.gen.o' failed
make[2]: *** [firmware/exynos8895_acpm_dvfs.fw.gen.o] Error 1
/work2/projects/Android/cm/system/kernel/samsung/universal8895/Makefile:998:
recipe for target 'firmware' failed
```

This error is a bit weirder, the build finds firmware/exynos8895_acpm_dvfs.fw in the source directory but it doesn't copy it to the build directory for some reason.

[exynos8895_acpm_dvfs.fw](https://github.com/Vaughnellope/android_kernel_samsung_universal8895/blob/lineage-15.1/firmware/exynos8895_acpm_dvfs.fw) is generated from [exynos8895_acpm_dvfs.fw.ihex](https://github.com/Vaughnellope/android_kernel_samsung_universal8895/blob/lineage-15.1/firmware/exynos8895_acpm_dvfs.fw.ihex) though using the [ihex2fw utility](https://github.com/Vaughnellope/android_kernel_samsung_universal8895/blob/lineage-15.1/firmware/ihex2fw.c), so having both files is a bit unnecessary in either case (unless exynos8895_acpm_dvfs.fw contains something exynos8895_acpm_dvfs.fw.ihex doesn't generate?).

Removing it makes the build generate it from the .ihex into the build folder and the build thereafter proceeds and eventually finishes.

---

Here's the local_manifest I've been using: 
```
<?xml version="1.0" encoding="UTF-8"?>

<manifest>
  <remote name="zx2c4" fetch="https://git.zx2c4.com/" />
  
  <project name="Universal8895/android_device_samsung_dream2lte"
	   path="device/samsung/dream2lte"
	   remote="github"
	   revision="refs/heads/lineage-15.1" />
  <project name="Grimler91/android_kernel_samsung_universal8895"
	   path="kernel/samsung/universal8895"
	   remote="github"
	   revision="refs/heads/lineage-15.1" />
  <project name="Fevax/android_device_samsung_universal8895-common"
	   path="device/samsung/universal8895-common"
	   remote="github" />
  <project name="Universal8895/android_hardware_samsung_slsi-cm_exynos8895"
	   path="hardware/samsung_slsi-cm/exynos8895"
	   remote="github"
	   revision="refs/heads/lineage-15.1" />
  <project name="Universal8895/proprietary_vendor_samsung-muppets"
	   path="vendor/samsung"
	   revision="refs/heads/lineage-15.1" />
  <project name="LineageOS/android_hardware_samsung"
	   path="hardware/samsung"
	   remote="github" />
  <project name="LineageOS/android_packages_resources_devicesettings"
	   path="packages/resources/devicesettings"
	   remote="github" />
  <project remote="zx2c4"
	   name="android_kernel_wireguard"
	   path="kernel/wireguard"
	   revision="master"
	   sync-s="true" />
</manifest>
```

**Comment by Vaughnellope** [comment]
you know what, im gonna redo the kernel, this is a total mess. but thanks for pointing me out that error exists here, i havent touch this source for ages

**Pull request merged**
